<?php
/**** WE ARE ONLY WORRIED ABOUT THE LOBBY WALL AT THIS POINT DO NOT PAY ATTENTION TO THE DISPLAY ***/


function execute_events_cronapi($op, $function = NULL) {
 
  switch($op) {
    case 'list':
      return array(
        'execute_events_cronjob' => 'Execute Any Scheduled Content',
      );
    case 'rule':
      switch($function) {
        case 'execute_events_cronjob': return '*/5 * * * *';
      }
      break;
    case 'execute':
      switch($function) {
        case 'execute_events_cronjob':
          execute_events_start();
          break;
      }
      break;
    case 'settings':
      switch ($function) {
        case 'execute_events_cronjob': return array('enabled' => TRUE);
      }
  }
 
}

// Custom cron-function
function execute_events_start() {
    $LOBBY_NID = 149;

    $query = new EntityFieldQuery;
    $result = $query
       ->entityCondition('entity_type', 'node')
       ->propertyCondition('type', 'scheduled_content')
       ->propertyCondition('status', 1) // Getting published nodes only.
       ->fieldCondition('field_date', 'value', date('Y-m-d H:i:00'), '=')
       ->execute();

    if (isset($result["node"])){ //Look for Start Date
        $node_uids = array_keys($result["node"]);
        $e = node_load($node_uids[0]); //only get the first one

        $scenario = field_collection_item_load($e->field_scenario['und'][0]['value']);
        
        $interactiveNode = node_load($LOBBY_NID);
        $interactiveScenario = field_collection_item_load($interactiveNode->field_scenario['und'][0]['value']);

        $interactiveScenario->field_default_scenario['und'][0]['tid'] = $scenario->field_default_scenario['und'][0]['tid'];
        $interactiveScenario->field_slideshow['und'][0]['target_id'] = $scenario->field_slideshow['und'][0]['target_id'];
        $interactiveScenario->field_video_scenario['und'][0]['target_id'] = $scenario->field_video_scenario['und'][0]['target_id'];
        
        entity_save('field_collection_item',$interactiveScenario);
    }
    else { //Look for schedule events that matches the end date
        $query = new EntityFieldQuery;
        $result = $query
            ->entityCondition('entity_type', 'node')
            ->propertyCondition('type', 'scheduled_content')
            ->propertyCondition('status', 1) // Getting published nodes only.
            ->fieldCondition('field_date', 'value2', date('Y-m-d H:i:00'), '=')
            ->execute();

        if (isset($result["node"])){ //Check to see if scheduled event is finished
            //Try to see if there is anything else that is running and if there is switch to it
            $query = new EntityFieldQuery;
            $result = $query
                ->entityCondition('entity_type', 'node')
                ->propertyCondition('type', 'scheduled_content')
                ->propertyCondition('status', 1) // Getting published nodes only.
                ->fieldCondition('field_date', 'value', date('Y-m-d H:i:00'), '<')
                ->fieldCondition('field_date', 'value2', date('Y-m-d H:i:00'), '>')
                ->execute();

            if (isset($result["node"])){
                $node_uids = array_keys($result["node"]);

                //need to verify there is only one on a repeating date
                for ($i = 0; $i < count($node_uids); $i++){
                   $e = node_load($node_uids[$i]); //only get the first one
                   
                   for ($j = 0; $j < count($e->field_date['und']); $j++){
                        $value1 = date_create($e->field_date['und'][$j]['value']);
                        $value1 = date_format($value1,"Y-m-d H:i:s");

                        $value2 = date_create($e->field_date['und'][$j]['value2']);
                        $value2 = date_format($value2,"Y-m-d H:i:s");
                        
                        if( strtotime($value1) < strtotime('now') && strtotime($value2) > strtotime('now')) {
                            $scenario = field_collection_item_load($e->field_scenario['und'][0]['value']);

                            $interactiveNode = node_load($LOBBY_NID);
                            $interactiveScenario = field_collection_item_load($interactiveNode->field_scenario['und'][0]['value']);

                            $interactiveScenario->field_default_scenario['und'][0]['tid'] = $scenario->field_default_scenario['und'][0]['tid'];
                            $interactiveScenario->field_slideshow['und'][0]['target_id'] = $scenario->field_slideshow['und'][0]['target_id'];
                            $interactiveScenario->field_video_scenario['und'][0]['target_id'] = $scenario->field_video_scenario['und'][0]['target_id'];

                            entity_save('field_collection_item',$interactiveScenario);
                        }
                    }
                }
            }
        }
    }
}

?>

